### ISSUE TITLE
Port-forward: upgrade request required

### ISSUE THREAD

**Issue by lvermeulen** [tmds/dotnet-mssql-ex#5]
Hi Tom,

When I try to follow your instructions in README.md, when I get to "oc port-forward [[pod-name]] 1433 I always get the response: "error: error upgrading connection: Upgrade request required".

In Postman I see this response:
{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Upgrade request required",
    "reason": "BadRequest",
    "code": 400
}

Do you have any idea what is causing this, and maybe have a solution? As it is, it's difficult to manage a SQL Server that I cannot access. :-)

**Comment by tmds** [comment]
I guess there is an issue upgrading the HTTP connection. Try using a different version of the [client-tools](https://github.com/openshift/origin/releases): either the latest, or the one that matches your OpenShift server version.

**Comment by tmds** [comment]
If there is a proxy server in your setup, it may also get in the way of the HTTP upgrade.

**Comment by lvermeulen** [comment]
I tried oc versions 3.9, 3.10 and 3.11 - no luck. I'm not using a proxy AFAIK. I even shut down the GlobalProtect UI and service.

**Comment by tmds** [comment]
Where is your OpenShift server running? There is a Red Hat KB article that describes issues with the AWS Elastic Load Balancer: https://access.redhat.com/solutions/3149531.

**Comment by lvermeulen** [comment]
It's at https://master.dev-ocp.tuiwestern.eu:443

I can't see any of the responses in that KB article, it requires a subscription of sorts.

**Comment by tmds** [comment]
Looks like it is running on aws.
```
$ whois tuiwestern.eu
[Querying whois.eu]
[whois.eu]
...

Name servers:
        ns-1271.awsdns-30.org
        ns-187.awsdns-23.com
        ns-869.awsdns-44.net
        ns-1772.awsdns-29.co.uk
```
so that _might_ be the issue. You need a red hat subscription to access the KB. You may be able to access it using the no-cost developer subscription (https://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available/). If that is the issue, it requires changing the AWS load balancer settings.

**Comment by lvermeulen** [comment]
I will talk to the admins about that, I'm not admin myself. Thanks a lot for your support!
